language: php

cache:
  directories:
    - "$HOME/.composer/cache"

php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - 'nightly'

matrix:
  fast_finish: true
  include:
    - php: '5.3'
      env: COMPOSER_FLAGS='--prefer-lowest'
  allow_failures:
    - php: nightly

before_install:
  - composer global config repositories.bin path $PWD
  - composer global require bamarni/composer-bin-plugin:dev-master

install:
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: false
